pool:
  nodes:
    - id: "node_1"
      dsn: "postgres://postgres:readyset@localhost:5433/testdb"
      internal_host: "postgres"
      internal_port: 5432
    - id: "node_2"
      dsn: "postgres://postgres:readyset@localhost:5434/testdb"
      internal_host: "postgres2"
      internal_port: 5432
    - id: "node_3"
      dsn: "postgres://postgres:readyset@localhost:5435/testdb"
      internal_host: "postgres3"
      internal_port: 5432
zookeeper:
  - "localhost:2181"
  - "localhost:2182"
  - "localhost:2183"

nodes_path: "/nodes"